name: Postman tests
on:
  push:
    branches: [main, dev/postman-tests]
jobs:
  run-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name:
        uses: actions/checkout@v2

      - name: Set up Prisma
        run: |
          cd next
          npm i
          npx prisma generate
          npx prisma migrate reset --force
          npx prisma migrate dev
          npx prisma db seed

      - name: Start API
        run: |
          cd next
          npm i
          npm run dev &
          sleep 10

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: next/postman/WebsiteTheSSEquelTests.postman_collection.json
          environment: next/postman/WebsiteTheSSEquelTests.postman_collection.json
          reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
